spring.config.import=optional:file:./src/main/resources/secret.properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url= jdbc:postgresql://localhost:5432/springboottemplate
spring.datasource.username=postgres
spring.datasource.password=prizrenkosova04
jwt.token.secret=123
spring.main.allow-circular-references=true

